### ISSUE TITLE
Js rounding for values <0 is 0

### ISSUE THREAD

**Issue by Wardormeur** [licoffe/POE-Stash-indexer#8] opened 2016-12-21 23:14 UTC
To reproduce : 
Search for gloves with
#% of Physical Attack Damage Leeched as Life
Expected : 
0.xx% LL
Result
0% LL

**Comment by licoffe** [comment] 2016-12-21 23:31
Thanks for the heads-up! It's the same with all float values on mods. The indexer inserts the data into the DB which truncates it because the field is of type smallint. I'll change that and reupload the new schema and it should be fixed.

**Comment by licoffe** [comment] 2016-12-22 08:56
I can confirm it's now fixed ([screen](http://imgur.com/a/RPNRT)). New life leech mods started showing up without rounded values. I'll upload the schema.sql modifications soon.

**Closed as completed by licoffe** 2016-12-22 08:56 UTC

**Comment by Wardormeur** [comment] 2016-12-22 15:50
Great, thanks :)
